### ISSUE TITLE
really?

### ISSUE THREAD

**Issue by karenetheridge** [perlancar/perl-Dist-Zilla-Plugin-For-Data-Sah#1]
Really, a distribution that is only useful for one and only one distribution?

Why not instead write your custom plugin in inc/Foo.pm, and include it in dist.ini as `[=inc::Foo]`?

**Comment by perlancar** [comment]
> Really, a distribution that is only useful for one and only one distribution?

This is not that different from a plugin bundle like Dist::Zilla::PluginBundle::Author::Foo, except that instead of for building distribution of a specific author, this is for building for a specific distribution. Also, I envision this plugin will also be used for Data-Sah-Type-\* distribution that introduces extra types.

> Why not instead write your custom plugin in inc/Foo.pm, and include it in dist.ini as [=inc::Foo]?

I want to build 'Foo' the standard way also, like my normal distribution.
